/** Generated by scripts/contrast-audit.mjs — do not edit manually */
export const contrastAuditMeta = {
  auditedAt: "2026-06-26",
  standard: "WCAG 2.1 AA (4.5:1 normal text)",
  allThemesPass: true,
} as const

export const contrastAuditResults = [
  {
    "themeId": "brutalist",
    "mode": "light",
    "pass": true,
    "pairs": [
      {
        "label": "Body text",
        "ratio": 20.21,
        "pass": true,
        "fg": "foreground",
        "bg": "background"
      },
      {
        "label": "Primary button",
        "ratio": 20.2,
        "pass": true,
        "fg": "primary-foreground",
        "bg": "primary"
      },
      {
        "label": "Secondary surface",
        "ratio": 17.46,
        "pass": true,
        "fg": "secondary-foreground",
        "bg": "secondary"
      },
      {
        "label": "Muted text",
        "ratio": 9.2,
        "pass": true,
        "fg": "muted-foreground",
        "bg": "muted"
      },
      {
        "label": "Card text",
        "ratio": 20.79,
        "pass": true,
        "fg": "card-foreground",
        "bg": "card"
      },
      {
        "label": "Destructive button",
        "ratio": 5.54,
        "pass": true,
        "fg": "destructive-foreground",
        "bg": "destructive"
      }
    ]
  },
  {
    "themeId": "brutalist",
    "mode": "dark",
    "pass": true,
    "pairs": [
      {
        "label": "Body text",
        "ratio": 18.88,
        "pass": true,
        "fg": "foreground",
        "bg": "background"
      },
      {
        "label": "Primary button",
        "ratio": 19.06,
        "pass": true,
        "fg": "primary-foreground",
        "bg": "primary"
      },
      {
        "label": "Secondary surface",
        "ratio": 16.6,
        "pass": true,
        "fg": "secondary-foreground",
        "bg": "secondary"
      },
      {
        "label": "Muted text",
        "ratio": 7.3,
        "pass": true,
        "fg": "muted-foreground",
        "bg": "muted"
      },
      {
        "label": "Card text",
        "ratio": 18.25,
        "pass": true,
        "fg": "card-foreground",
        "bg": "card"
      },
      {
        "label": "Destructive button",
        "ratio": 8.75,
        "pass": true,
        "fg": "destructive-foreground",
        "bg": "destructive"
      }
    ]
  },
  {
    "themeId": "corporate",
    "mode": "light",
    "pass": true,
    "pairs": [
      {
        "label": "Body text",
        "ratio": 16.34,
        "pass": true,
        "fg": "foreground",
        "bg": "background"
      },
      {
        "label": "Primary button",
        "ratio": 6.42,
        "pass": true,
        "fg": "primary-foreground",
        "bg": "primary"
      },
      {
        "label": "Secondary surface",
        "ratio": 12.61,
        "pass": true,
        "fg": "secondary-foreground",
        "bg": "secondary"
      },
      {
        "label": "Muted text",
        "ratio": 6.9,
        "pass": true,
        "fg": "muted-foreground",
        "bg": "muted"
      },
      {
        "label": "Card text",
        "ratio": 17.3,
        "pass": true,
        "fg": "card-foreground",
        "bg": "card"
      },
      {
        "label": "Destructive button",
        "ratio": 5.84,
        "pass": true,
        "fg": "destructive-foreground",
        "bg": "destructive"
      }
    ]
  },
  {
    "themeId": "corporate",
    "mode": "dark",
    "pass": true,
    "pairs": [
      {
        "label": "Body text",
        "ratio": 16.8,
        "pass": true,
        "fg": "foreground",
        "bg": "background"
      },
      {
        "label": "Primary button",
        "ratio": 6.23,
        "pass": true,
        "fg": "primary-foreground",
        "bg": "primary"
      },
      {
        "label": "Secondary surface",
        "ratio": 13.43,
        "pass": true,
        "fg": "secondary-foreground",
        "bg": "secondary"
      },
      {
        "label": "Muted text",
        "ratio": 6.64,
        "pass": true,
        "fg": "muted-foreground",
        "bg": "muted"
      },
      {
        "label": "Card text",
        "ratio": 15.66,
        "pass": true,
        "fg": "card-foreground",
        "bg": "card"
      },
      {
        "label": "Destructive button",
        "ratio": 6.92,
        "pass": true,
        "fg": "destructive-foreground",
        "bg": "destructive"
      }
    ]
  },
  {
    "themeId": "editorial",
    "mode": "light",
    "pass": true,
    "pairs": [
      {
        "label": "Body text",
        "ratio": 16.44,
        "pass": true,
        "fg": "foreground",
        "bg": "background"
      },
      {
        "label": "Primary button",
        "ratio": 13.56,
        "pass": true,
        "fg": "primary-foreground",
        "bg": "primary"
      },
      {
        "label": "Secondary surface",
        "ratio": 12.41,
        "pass": true,
        "fg": "secondary-foreground",
        "bg": "secondary"
      },
      {
        "label": "Muted text",
        "ratio": 6.41,
        "pass": true,
        "fg": "muted-foreground",
        "bg": "muted"
      },
      {
        "label": "Card text",
        "ratio": 17.16,
        "pass": true,
        "fg": "card-foreground",
        "bg": "card"
      },
      {
        "label": "Destructive button",
        "ratio": 6.79,
        "pass": true,
        "fg": "destructive-foreground",
        "bg": "destructive"
      }
    ]
  },
  {
    "themeId": "editorial",
    "mode": "dark",
    "pass": true,
    "pairs": [
      {
        "label": "Body text",
        "ratio": 15.37,
        "pass": true,
        "fg": "foreground",
        "bg": "background"
      },
      {
        "label": "Primary button",
        "ratio": 13.16,
        "pass": true,
        "fg": "primary-foreground",
        "bg": "primary"
      },
      {
        "label": "Secondary surface",
        "ratio": 11.97,
        "pass": true,
        "fg": "secondary-foreground",
        "bg": "secondary"
      },
      {
        "label": "Muted text",
        "ratio": 6.31,
        "pass": true,
        "fg": "muted-foreground",
        "bg": "muted"
      },
      {
        "label": "Card text",
        "ratio": 14.17,
        "pass": true,
        "fg": "card-foreground",
        "bg": "card"
      },
      {
        "label": "Destructive button",
        "ratio": 6.73,
        "pass": true,
        "fg": "destructive-foreground",
        "bg": "destructive"
      }
    ]
  },
  {
    "themeId": "glass",
    "mode": "light",
    "pass": true,
    "pairs": [
      {
        "label": "Body text",
        "ratio": 13.71,
        "pass": true,
        "fg": "foreground",
        "bg": "background"
      },
      {
        "label": "Primary button",
        "ratio": 4.93,
        "pass": true,
        "fg": "primary-foreground",
        "bg": "primary"
      },
      {
        "label": "Secondary surface",
        "ratio": 16.09,
        "pass": true,
        "fg": "secondary-foreground",
        "bg": "secondary"
      },
      {
        "label": "Muted text",
        "ratio": 8.5,
        "pass": true,
        "fg": "muted-foreground",
        "bg": "muted"
      },
      {
        "label": "Card text",
        "ratio": 18.19,
        "pass": true,
        "fg": "card-foreground",
        "bg": "card"
      },
      {
        "label": "Destructive button",
        "ratio": 5.29,
        "pass": true,
        "fg": "destructive-foreground",
        "bg": "destructive"
      }
    ]
  },
  {
    "themeId": "glass",
    "mode": "dark",
    "pass": true,
    "pairs": [
      {
        "label": "Body text",
        "ratio": 16.82,
        "pass": true,
        "fg": "foreground",
        "bg": "background"
      },
      {
        "label": "Primary button",
        "ratio": 7.79,
        "pass": true,
        "fg": "primary-foreground",
        "bg": "primary"
      },
      {
        "label": "Secondary surface",
        "ratio": 11.84,
        "pass": true,
        "fg": "secondary-foreground",
        "bg": "secondary"
      },
      {
        "label": "Muted text",
        "ratio": 5.9,
        "pass": true,
        "fg": "muted-foreground",
        "bg": "muted"
      },
      {
        "label": "Card text",
        "ratio": 14.28,
        "pass": true,
        "fg": "card-foreground",
        "bg": "card"
      },
      {
        "label": "Destructive button",
        "ratio": 6.92,
        "pass": true,
        "fg": "destructive-foreground",
        "bg": "destructive"
      }
    ]
  },
  {
    "themeId": "luxury",
    "mode": "light",
    "pass": true,
    "pairs": [
      {
        "label": "Body text",
        "ratio": 19.73,
        "pass": true,
        "fg": "foreground",
        "bg": "background"
      },
      {
        "label": "Primary button",
        "ratio": 8.39,
        "pass": true,
        "fg": "primary-foreground",
        "bg": "primary"
      },
      {
        "label": "Secondary surface",
        "ratio": 16.74,
        "pass": true,
        "fg": "secondary-foreground",
        "bg": "secondary"
      },
      {
        "label": "Muted text",
        "ratio": 7.54,
        "pass": true,
        "fg": "muted-foreground",
        "bg": "muted"
      },
      {
        "label": "Card text",
        "ratio": 20.3,
        "pass": true,
        "fg": "card-foreground",
        "bg": "card"
      },
      {
        "label": "Destructive button",
        "ratio": 6.79,
        "pass": true,
        "fg": "destructive-foreground",
        "bg": "destructive"
      }
    ]
  },
  {
    "themeId": "luxury",
    "mode": "dark",
    "pass": true,
    "pairs": [
      {
        "label": "Body text",
        "ratio": 17.54,
        "pass": true,
        "fg": "foreground",
        "bg": "background"
      },
      {
        "label": "Primary button",
        "ratio": 8.64,
        "pass": true,
        "fg": "primary-foreground",
        "bg": "primary"
      },
      {
        "label": "Secondary surface",
        "ratio": 16.28,
        "pass": true,
        "fg": "secondary-foreground",
        "bg": "secondary"
      },
      {
        "label": "Muted text",
        "ratio": 6.91,
        "pass": true,
        "fg": "muted-foreground",
        "bg": "muted"
      },
      {
        "label": "Card text",
        "ratio": 17.27,
        "pass": true,
        "fg": "card-foreground",
        "bg": "card"
      },
      {
        "label": "Destructive button",
        "ratio": 6.73,
        "pass": true,
        "fg": "destructive-foreground",
        "bg": "destructive"
      }
    ]
  },
  {
    "themeId": "minimal",
    "mode": "light",
    "pass": true,
    "pairs": [
      {
        "label": "Body text",
        "ratio": 19.13,
        "pass": true,
        "fg": "foreground",
        "bg": "background"
      },
      {
        "label": "Primary button",
        "ratio": 5.4,
        "pass": true,
        "fg": "primary-foreground",
        "bg": "primary"
      },
      {
        "label": "Secondary surface",
        "ratio": 16.6,
        "pass": true,
        "fg": "secondary-foreground",
        "bg": "secondary"
      },
      {
        "label": "Muted text",
        "ratio": 6.44,
        "pass": true,
        "fg": "muted-foreground",
        "bg": "muted"
      },
      {
        "label": "Card text",
        "ratio": 19.41,
        "pass": true,
        "fg": "card-foreground",
        "bg": "card"
      },
      {
        "label": "Destructive button",
        "ratio": 5.29,
        "pass": true,
        "fg": "destructive-foreground",
        "bg": "destructive"
      }
    ]
  },
  {
    "themeId": "minimal",
    "mode": "dark",
    "pass": true,
    "pairs": [
      {
        "label": "Body text",
        "ratio": 18.21,
        "pass": true,
        "fg": "foreground",
        "bg": "background"
      },
      {
        "label": "Primary button",
        "ratio": 5.52,
        "pass": true,
        "fg": "primary-foreground",
        "bg": "primary"
      },
      {
        "label": "Secondary surface",
        "ratio": 16.12,
        "pass": true,
        "fg": "secondary-foreground",
        "bg": "secondary"
      },
      {
        "label": "Muted text",
        "ratio": 5.6,
        "pass": true,
        "fg": "muted-foreground",
        "bg": "muted"
      },
      {
        "label": "Card text",
        "ratio": 17.72,
        "pass": true,
        "fg": "card-foreground",
        "bg": "card"
      },
      {
        "label": "Destructive button",
        "ratio": 6.92,
        "pass": true,
        "fg": "destructive-foreground",
        "bg": "destructive"
      }
    ]
  },
  {
    "themeId": "neon",
    "mode": "light",
    "pass": true,
    "pairs": [
      {
        "label": "Body text",
        "ratio": 16.64,
        "pass": true,
        "fg": "foreground",
        "bg": "background"
      },
      {
        "label": "Primary button",
        "ratio": 11.25,
        "pass": true,
        "fg": "primary-foreground",
        "bg": "primary"
      },
      {
        "label": "Secondary surface",
        "ratio": 13.02,
        "pass": true,
        "fg": "secondary-foreground",
        "bg": "secondary"
      },
      {
        "label": "Muted text",
        "ratio": 6.01,
        "pass": true,
        "fg": "muted-foreground",
        "bg": "muted"
      },
      {
        "label": "Card text",
        "ratio": 16.13,
        "pass": true,
        "fg": "card-foreground",
        "bg": "card"
      },
      {
        "label": "Destructive button",
        "ratio": 5.84,
        "pass": true,
        "fg": "destructive-foreground",
        "bg": "destructive"
      }
    ]
  },
  {
    "themeId": "neon",
    "mode": "dark",
    "pass": true,
    "pairs": [
      {
        "label": "Body text",
        "ratio": 17.92,
        "pass": true,
        "fg": "foreground",
        "bg": "background"
      },
      {
        "label": "Primary button",
        "ratio": 13.1,
        "pass": true,
        "fg": "primary-foreground",
        "bg": "primary"
      },
      {
        "label": "Secondary surface",
        "ratio": 14.83,
        "pass": true,
        "fg": "secondary-foreground",
        "bg": "secondary"
      },
      {
        "label": "Muted text",
        "ratio": 7.68,
        "pass": true,
        "fg": "muted-foreground",
        "bg": "muted"
      },
      {
        "label": "Card text",
        "ratio": 17.69,
        "pass": true,
        "fg": "card-foreground",
        "bg": "card"
      },
      {
        "label": "Destructive button",
        "ratio": 6.58,
        "pass": true,
        "fg": "destructive-foreground",
        "bg": "destructive"
      }
    ]
  },
  {
    "themeId": "organic",
    "mode": "light",
    "pass": true,
    "pairs": [
      {
        "label": "Body text",
        "ratio": 12.91,
        "pass": true,
        "fg": "foreground",
        "bg": "background"
      },
      {
        "label": "Primary button",
        "ratio": 5.99,
        "pass": true,
        "fg": "primary-foreground",
        "bg": "primary"
      },
      {
        "label": "Secondary surface",
        "ratio": 5.89,
        "pass": true,
        "fg": "secondary-foreground",
        "bg": "secondary"
      },
      {
        "label": "Muted text",
        "ratio": 6.24,
        "pass": true,
        "fg": "muted-foreground",
        "bg": "muted"
      },
      {
        "label": "Card text",
        "ratio": 13.65,
        "pass": true,
        "fg": "card-foreground",
        "bg": "card"
      },
      {
        "label": "Destructive button",
        "ratio": 6.14,
        "pass": true,
        "fg": "destructive-foreground",
        "bg": "destructive"
      }
    ]
  },
  {
    "themeId": "organic",
    "mode": "dark",
    "pass": true,
    "pairs": [
      {
        "label": "Body text",
        "ratio": 14.84,
        "pass": true,
        "fg": "foreground",
        "bg": "background"
      },
      {
        "label": "Primary button",
        "ratio": 8.07,
        "pass": true,
        "fg": "primary-foreground",
        "bg": "primary"
      },
      {
        "label": "Secondary surface",
        "ratio": 7.96,
        "pass": true,
        "fg": "secondary-foreground",
        "bg": "secondary"
      },
      {
        "label": "Muted text",
        "ratio": 6.25,
        "pass": true,
        "fg": "muted-foreground",
        "bg": "muted"
      },
      {
        "label": "Card text",
        "ratio": 13.62,
        "pass": true,
        "fg": "card-foreground",
        "bg": "card"
      },
      {
        "label": "Destructive button",
        "ratio": 6.71,
        "pass": true,
        "fg": "destructive-foreground",
        "bg": "destructive"
      }
    ]
  },
  {
    "themeId": "playful",
    "mode": "light",
    "pass": true,
    "pairs": [
      {
        "label": "Body text",
        "ratio": 13.61,
        "pass": true,
        "fg": "foreground",
        "bg": "background"
      },
      {
        "label": "Primary button",
        "ratio": 5.5,
        "pass": true,
        "fg": "primary-foreground",
        "bg": "primary"
      },
      {
        "label": "Secondary surface",
        "ratio": 10.21,
        "pass": true,
        "fg": "secondary-foreground",
        "bg": "secondary"
      },
      {
        "label": "Muted text",
        "ratio": 5.55,
        "pass": true,
        "fg": "muted-foreground",
        "bg": "muted"
      },
      {
        "label": "Card text",
        "ratio": 14.58,
        "pass": true,
        "fg": "card-foreground",
        "bg": "card"
      },
      {
        "label": "Destructive button",
        "ratio": 4.65,
        "pass": true,
        "fg": "destructive-foreground",
        "bg": "destructive"
      }
    ]
  },
  {
    "themeId": "playful",
    "mode": "dark",
    "pass": true,
    "pairs": [
      {
        "label": "Body text",
        "ratio": 14.96,
        "pass": true,
        "fg": "foreground",
        "bg": "background"
      },
      {
        "label": "Primary button",
        "ratio": 8.79,
        "pass": true,
        "fg": "primary-foreground",
        "bg": "primary"
      },
      {
        "label": "Secondary surface",
        "ratio": 8.98,
        "pass": true,
        "fg": "secondary-foreground",
        "bg": "secondary"
      },
      {
        "label": "Muted text",
        "ratio": 5.74,
        "pass": true,
        "fg": "muted-foreground",
        "bg": "muted"
      },
      {
        "label": "Card text",
        "ratio": 12.76,
        "pass": true,
        "fg": "card-foreground",
        "bg": "card"
      },
      {
        "label": "Destructive button",
        "ratio": 6.92,
        "pass": true,
        "fg": "destructive-foreground",
        "bg": "destructive"
      }
    ]
  },
  {
    "themeId": "retro",
    "mode": "light",
    "pass": true,
    "pairs": [
      {
        "label": "Body text",
        "ratio": 12.41,
        "pass": true,
        "fg": "foreground",
        "bg": "background"
      },
      {
        "label": "Primary button",
        "ratio": 5.71,
        "pass": true,
        "fg": "primary-foreground",
        "bg": "primary"
      },
      {
        "label": "Secondary surface",
        "ratio": 6.2,
        "pass": true,
        "fg": "secondary-foreground",
        "bg": "secondary"
      },
      {
        "label": "Muted text",
        "ratio": 6.38,
        "pass": true,
        "fg": "muted-foreground",
        "bg": "muted"
      },
      {
        "label": "Card text",
        "ratio": 13.55,
        "pass": true,
        "fg": "card-foreground",
        "bg": "card"
      },
      {
        "label": "Destructive button",
        "ratio": 6.01,
        "pass": true,
        "fg": "destructive-foreground",
        "bg": "destructive"
      }
    ]
  },
  {
    "themeId": "retro",
    "mode": "dark",
    "pass": true,
    "pairs": [
      {
        "label": "Body text",
        "ratio": 14.91,
        "pass": true,
        "fg": "foreground",
        "bg": "background"
      },
      {
        "label": "Primary button",
        "ratio": 7.59,
        "pass": true,
        "fg": "primary-foreground",
        "bg": "primary"
      },
      {
        "label": "Secondary surface",
        "ratio": 6.47,
        "pass": true,
        "fg": "secondary-foreground",
        "bg": "secondary"
      },
      {
        "label": "Muted text",
        "ratio": 6.2,
        "pass": true,
        "fg": "muted-foreground",
        "bg": "muted"
      },
      {
        "label": "Card text",
        "ratio": 13.13,
        "pass": true,
        "fg": "card-foreground",
        "bg": "card"
      },
      {
        "label": "Destructive button",
        "ratio": 6.73,
        "pass": true,
        "fg": "destructive-foreground",
        "bg": "destructive"
      }
    ]
  }
] as const

export type ContrastAuditEntry = (typeof contrastAuditResults)[number]
