/** Generated by scripts/lighthouse-audit.mjs — do not edit manually */
export const lighthouseAuditMeta = {
  auditedAt: "2026-06-26",
  available: true,
  perfBudget: 95,
} as const

export const lighthouseAuditResults = {
  "home": {
    "mobile": {
      "performance": 73,
      "accessibility": 94,
      "bestPractices": 100,
      "seo": 100
    },
    "desktop": {
      "performance": 97,
      "accessibility": 100,
      "bestPractices": 100,
      "seo": 100
    }
  },
  "preview": {
    "mobile": {
      "performance": 71,
      "accessibility": 95,
      "bestPractices": 100,
      "seo": 100
    },
    "desktop": {
      "performance": 93,
      "accessibility": 100,
      "bestPractices": 100,
      "seo": 100
    }
  },
  "docs": {
    "mobile": {
      "performance": 81,
      "accessibility": 94,
      "bestPractices": 100,
      "seo": 100
    },
    "desktop": {
      "performance": 99,
      "accessibility": 100,
      "bestPractices": 100,
      "seo": 100
    }
  }
} as const

export const lighthouseMinPerformance = 71 as const
