import * as Blocks from "@/components/blocks/block-exports"
import type { CatalogEntry, CategoryMeta } from "@/types/catalog"

export const blockComponents = {
  NavbarSimple: Blocks.NavbarSimple,
  NavbarWithCta: Blocks.NavbarWithCta,
  HeroCentered: Blocks.HeroCentered,
  HeroSplit: Blocks.HeroSplit,
  HeroGradient: Blocks.HeroGradient,
  FeatureGridThree: Blocks.FeatureGridThree,
  FeatureGridBento: Blocks.FeatureGridBento,
  LogoCloudSimple: Blocks.LogoCloudSimple,
  LogoCloudWithHeading: Blocks.LogoCloudWithHeading,
  TestimonialCards: Blocks.TestimonialCards,
  TestimonialSingle: Blocks.TestimonialSingle,
  PricingThreeTier: Blocks.PricingThreeTier,
  PricingTwoTier: Blocks.PricingTwoTier,
  FaqAccordion: Blocks.FaqAccordion,
  FaqTwoColumn: Blocks.FaqTwoColumn,
  CtaCentered: Blocks.CtaCentered,
  CtaSplit: Blocks.CtaSplit,
  StatsRow: Blocks.StatsRow,
  StatsWithDescription: Blocks.StatsWithDescription,
  NewsletterInline: Blocks.NewsletterInline,
  NewsletterCard: Blocks.NewsletterCard,
  FooterSimple: Blocks.FooterSimple,
  FooterColumns: Blocks.FooterColumns,
  LoginSimple: Blocks.LoginSimple,
  LoginWithSocial: Blocks.LoginWithSocial,
  SignupSimple: Blocks.SignupSimple,
  SignupWithTerms: Blocks.SignupWithTerms,
  ForgotPasswordSimple: Blocks.ForgotPasswordSimple,
  ForgotPasswordCard: Blocks.ForgotPasswordCard,
  OtpVerifySimple: Blocks.OtpVerifySimple,
  OtpVerifyCard: Blocks.OtpVerifyCard,
  TwoColumnAuthImage: Blocks.TwoColumnAuthImage,
  TwoColumnAuthSplit: Blocks.TwoColumnAuthSplit,
  AppShellSidebar: Blocks.AppShellSidebar,
  AppShellCompact: Blocks.AppShellCompact,
  StatsCardsRow: Blocks.StatsCardsRow,
  StatsCardsWithTrend: Blocks.StatsCardsWithTrend,
  ChartsPanelBar: Blocks.ChartsPanelBar,
  ChartsPanelMixed: Blocks.ChartsPanelMixed,
  DataTablePage: Blocks.DataTablePage,
  SettingsPageTabs: Blocks.SettingsPageTabs,
  SettingsPageSidebar: Blocks.SettingsPageSidebar,
  ProfilePageSimple: Blocks.ProfilePageSimple,
  ProfilePageDetailed: Blocks.ProfilePageDetailed,
  EmptyStateSimple: Blocks.EmptyStateSimple,
  EmptyStateWithAction: Blocks.EmptyStateWithAction,
  NotificationsPanelList: Blocks.NotificationsPanelList,
  NotificationsPanelGrouped: Blocks.NotificationsPanelGrouped,
  ProductGridSimple: Blocks.ProductGridSimple,
  ProductGridFeatured: Blocks.ProductGridFeatured,
  ProductDetailSimple: Blocks.ProductDetailSimple,
  ProductDetailGallery: Blocks.ProductDetailGallery,
  CartDrawer: Blocks.CartDrawer,
  CheckoutFormSimple: Blocks.CheckoutFormSimple,
  CheckoutFormMultiStep: Blocks.CheckoutFormMultiStep,
  BlogListGrid: Blocks.BlogListGrid,
  BlogListFeatured: Blocks.BlogListFeatured,
  BlogPostSimple: Blocks.BlogPostSimple,
  BlogPostWithSidebar: Blocks.BlogPostWithSidebar,
  DocsLayoutSidebar: Blocks.DocsLayoutSidebar,
  DocsLayoutToc: Blocks.DocsLayoutToc,
} as const

export type BlockComponentKey = keyof typeof blockComponents

function snippet(component: string, importPath: string) {
  return `import { ${component} } from "${importPath}"

export default function Page() {
  return <${component} />
}`
}

export type BlockCategory =
  | "marketing"
  | "auth"
  | "application"
  | "commerce"
  | "content"

export const blockCategoryMeta: Record<BlockCategory, CategoryMeta> = {
  marketing: {
    label: "Marketing",
    description: "Landing pages, pricing, and conversion sections",
  },
  auth: {
    label: "Auth",
    description: "Sign-in flows and verification screens",
  },
  application: {
    label: "Application",
    description: "Dashboard shells, settings, and app UI",
  },
  commerce: {
    label: "Commerce",
    description: "Product, cart, and checkout experiences",
  },
  content: {
    label: "Content",
    description: "Blog, docs, and editorial layouts",
  },
}

export interface BlockEntry extends CatalogEntry<BlockCategory> {
  componentKey: BlockComponentKey
  importPath: string
  fullWidth?: boolean
}

export const blockEntries: BlockEntry[] = [
  // Marketing
  {
    id: "navbar-simple",
    name: "Navbar — Simple",
    category: "marketing",
    description: "Logo, links, and mobile menu",
    componentKey: "NavbarSimple",
    importPath: "@/components/blocks/marketing/navbar",
  },
  {
    id: "navbar-cta",
    name: "Navbar — With CTA",
    category: "marketing",
    description: "Navigation with primary call-to-action",
    componentKey: "NavbarWithCta",
    importPath: "@/components/blocks/marketing/navbar",
  },
  {
    id: "hero-centered",
    name: "Hero — Centered",
    category: "marketing",
    description: "Centered headline and dual CTAs",
    componentKey: "HeroCentered",
    importPath: "@/components/blocks/marketing/hero",
  },
  {
    id: "hero-split",
    name: "Hero — Split",
    category: "marketing",
    description: "Copy left, visual right",
    componentKey: "HeroSplit",
    importPath: "@/components/blocks/marketing/hero",
  },
  {
    id: "hero-gradient",
    name: "Hero — Gradient",
    category: "marketing",
    description: "Bold gradient backdrop hero",
    componentKey: "HeroGradient",
    importPath: "@/components/blocks/marketing/hero",
  },
  {
    id: "feature-grid-three",
    name: "Feature Grid — Three",
    category: "marketing",
    description: "Three-column feature cards",
    componentKey: "FeatureGridThree",
    importPath: "@/components/blocks/marketing/feature-grid",
  },
  {
    id: "feature-grid-bento",
    name: "Feature Grid — Bento",
    category: "marketing",
    description: "Asymmetric bento layout",
    componentKey: "FeatureGridBento",
    importPath: "@/components/blocks/marketing/feature-grid",
  },
  {
    id: "logo-cloud-simple",
    name: "Logo Cloud — Simple",
    category: "marketing",
    description: "Trusted-by logo row",
    componentKey: "LogoCloudSimple",
    importPath: "@/components/blocks/marketing/logo-cloud",
  },
  {
    id: "logo-cloud-heading",
    name: "Logo Cloud — With Heading",
    category: "marketing",
    description: "Logo strip with intro copy",
    componentKey: "LogoCloudWithHeading",
    importPath: "@/components/blocks/marketing/logo-cloud",
  },
  {
    id: "testimonial-cards",
    name: "Testimonial — Cards",
    category: "marketing",
    description: "Grid of customer quotes",
    componentKey: "TestimonialCards",
    importPath: "@/components/blocks/marketing/testimonial",
  },
  {
    id: "testimonial-single",
    name: "Testimonial — Single",
    category: "marketing",
    description: "Featured quote spotlight",
    componentKey: "TestimonialSingle",
    importPath: "@/components/blocks/marketing/testimonial",
  },
  {
    id: "pricing-three-tier",
    name: "Pricing — Three Tier",
    category: "marketing",
    description: "Starter, Pro, Enterprise",
    componentKey: "PricingThreeTier",
    importPath: "@/components/blocks/marketing/pricing",
    fullWidth: true,
  },
  {
    id: "pricing-two-tier",
    name: "Pricing — Two Tier",
    category: "marketing",
    description: "Simplified two-plan layout",
    componentKey: "PricingTwoTier",
    importPath: "@/components/blocks/marketing/pricing",
    fullWidth: true,
  },
  {
    id: "faq-accordion",
    name: "FAQ — Accordion",
    category: "marketing",
    description: "Expandable questions",
    componentKey: "FaqAccordion",
    importPath: "@/components/blocks/marketing/faq",
  },
  {
    id: "faq-two-column",
    name: "FAQ — Two Column",
    category: "marketing",
    description: "Split FAQ layout",
    componentKey: "FaqTwoColumn",
    importPath: "@/components/blocks/marketing/faq",
  },
  {
    id: "cta-centered",
    name: "CTA — Centered",
    category: "marketing",
    description: "Full-width conversion band",
    componentKey: "CtaCentered",
    importPath: "@/components/blocks/marketing/cta",
    fullWidth: true,
  },
  {
    id: "cta-split",
    name: "CTA — Split",
    category: "marketing",
    description: "Copy and action side by side",
    componentKey: "CtaSplit",
    importPath: "@/components/blocks/marketing/cta",
    fullWidth: true,
  },
  {
    id: "stats-row",
    name: "Stats — Row",
    category: "marketing",
    description: "Key metrics in a row",
    componentKey: "StatsRow",
    importPath: "@/components/blocks/marketing/stats",
    fullWidth: true,
  },
  {
    id: "stats-description",
    name: "Stats — With Description",
    category: "marketing",
    description: "Metrics with context copy",
    componentKey: "StatsWithDescription",
    importPath: "@/components/blocks/marketing/stats",
    fullWidth: true,
  },
  {
    id: "newsletter-inline",
    name: "Newsletter — Inline",
    category: "marketing",
    description: "Horizontal email capture",
    componentKey: "NewsletterInline",
    importPath: "@/components/blocks/marketing/newsletter",
    fullWidth: true,
  },
  {
    id: "newsletter-card",
    name: "Newsletter — Card",
    category: "marketing",
    description: "Contained signup card",
    componentKey: "NewsletterCard",
    importPath: "@/components/blocks/marketing/newsletter",
  },
  {
    id: "footer-simple",
    name: "Footer — Simple",
    category: "marketing",
    description: "Minimal footer bar",
    componentKey: "FooterSimple",
    importPath: "@/components/blocks/marketing/footer",
    fullWidth: true,
  },
  {
    id: "footer-columns",
    name: "Footer — Columns",
    category: "marketing",
    description: "Multi-column site footer",
    componentKey: "FooterColumns",
    importPath: "@/components/blocks/marketing/footer",
    fullWidth: true,
  },
  // Auth
  {
    id: "login-simple",
    name: "Login — Simple",
    category: "auth",
    description: "Email and password form",
    componentKey: "LoginSimple",
    importPath: "@/components/blocks/auth/login",
  },
  {
    id: "login-social",
    name: "Login — With Social",
    category: "auth",
    description: "OAuth divider and providers",
    componentKey: "LoginWithSocial",
    importPath: "@/components/blocks/auth/login",
  },
  {
    id: "signup-simple",
    name: "Signup — Simple",
    category: "auth",
    description: "Account creation form",
    componentKey: "SignupSimple",
    importPath: "@/components/blocks/auth/signup",
  },
  {
    id: "signup-terms",
    name: "Signup — With Terms",
    category: "auth",
    description: "Terms checkbox and legal copy",
    componentKey: "SignupWithTerms",
    importPath: "@/components/blocks/auth/signup",
  },
  {
    id: "forgot-simple",
    name: "Forgot Password — Simple",
    category: "auth",
    description: "Reset email request",
    componentKey: "ForgotPasswordSimple",
    importPath: "@/components/blocks/auth/forgot-password",
  },
  {
    id: "forgot-card",
    name: "Forgot Password — Card",
    category: "auth",
    description: "Card-wrapped reset flow",
    componentKey: "ForgotPasswordCard",
    importPath: "@/components/blocks/auth/forgot-password",
  },
  {
    id: "otp-simple",
    name: "OTP Verify — Simple",
    category: "auth",
    description: "Six-digit code entry",
    componentKey: "OtpVerifySimple",
    importPath: "@/components/blocks/auth/otp-verify",
  },
  {
    id: "otp-card",
    name: "OTP Verify — Card",
    category: "auth",
    description: "Verification in a card",
    componentKey: "OtpVerifyCard",
    importPath: "@/components/blocks/auth/otp-verify",
  },
  {
    id: "auth-image",
    name: "Auth — Two Column Image",
    category: "auth",
    description: "Form beside brand visual",
    componentKey: "TwoColumnAuthImage",
    importPath: "@/components/blocks/auth/two-column-auth",
    fullWidth: true,
  },
  {
    id: "auth-split",
    name: "Auth — Two Column Split",
    category: "auth",
    description: "Balanced split auth layout",
    componentKey: "TwoColumnAuthSplit",
    importPath: "@/components/blocks/auth/two-column-auth",
    fullWidth: true,
  },
  // Application
  {
    id: "app-shell-sidebar",
    name: "App Shell — Sidebar",
    category: "application",
    description: "Sidebar navigation + top bar",
    componentKey: "AppShellSidebar",
    importPath: "@/components/blocks/application/app-shell",
    fullWidth: true,
  },
  {
    id: "app-shell-compact",
    name: "App Shell — Compact",
    category: "application",
    description: "Collapsed icon sidebar",
    componentKey: "AppShellCompact",
    importPath: "@/components/blocks/application/app-shell",
    fullWidth: true,
  },
  {
    id: "stats-cards-row",
    name: "Stats Cards — Row",
    category: "application",
    description: "Dashboard KPI cards",
    componentKey: "StatsCardsRow",
    importPath: "@/components/blocks/application/stats-cards",
    fullWidth: true,
  },
  {
    id: "stats-cards-trend",
    name: "Stats Cards — With Trend",
    category: "application",
    description: "KPIs with delta indicators",
    componentKey: "StatsCardsWithTrend",
    importPath: "@/components/blocks/application/stats-cards",
    fullWidth: true,
  },
  {
    id: "charts-bar",
    name: "Charts Panel — Bar",
    category: "application",
    description: "Bar chart dashboard panel",
    componentKey: "ChartsPanelBar",
    importPath: "@/components/blocks/application/charts-panel",
    fullWidth: true,
  },
  {
    id: "charts-mixed",
    name: "Charts Panel — Mixed",
    category: "application",
    description: "Multi-metric chart layout",
    componentKey: "ChartsPanelMixed",
    importPath: "@/components/blocks/application/charts-panel",
    fullWidth: true,
  },
  {
    id: "data-table-page",
    name: "Data Table Page",
    category: "application",
    description: "Full page with filterable table",
    componentKey: "DataTablePage",
    importPath: "@/components/blocks/application/data-table-page",
    fullWidth: true,
  },
  {
    id: "settings-tabs",
    name: "Settings — Tabs",
    category: "application",
    description: "Tabbed settings sections",
    componentKey: "SettingsPageTabs",
    importPath: "@/components/blocks/application/settings-page",
    fullWidth: true,
  },
  {
    id: "settings-sidebar",
    name: "Settings — Sidebar Nav",
    category: "application",
    description: "Settings with side navigation",
    componentKey: "SettingsPageSidebar",
    importPath: "@/components/blocks/application/settings-page",
    fullWidth: true,
  },
  {
    id: "profile-simple",
    name: "Profile — Simple",
    category: "application",
    description: "Basic profile overview",
    componentKey: "ProfilePageSimple",
    importPath: "@/components/blocks/application/profile-page",
    fullWidth: true,
  },
  {
    id: "profile-detailed",
    name: "Profile — Detailed",
    category: "application",
    description: "Rich profile with activity",
    componentKey: "ProfilePageDetailed",
    importPath: "@/components/blocks/application/profile-page",
    fullWidth: true,
  },
  {
    id: "empty-simple",
    name: "Empty State — Simple",
    category: "application",
    description: "No data placeholder",
    componentKey: "EmptyStateSimple",
    importPath: "@/components/blocks/application/empty-state",
  },
  {
    id: "empty-action",
    name: "Empty State — With Action",
    category: "application",
    description: "Empty state with CTA",
    componentKey: "EmptyStateWithAction",
    importPath: "@/components/blocks/application/empty-state",
  },
  {
    id: "notifications-list",
    name: "Notifications — List",
    category: "application",
    description: "Chronological alerts",
    componentKey: "NotificationsPanelList",
    importPath: "@/components/blocks/application/notifications-panel",
  },
  {
    id: "notifications-grouped",
    name: "Notifications — Grouped",
    category: "application",
    description: "Grouped by time period",
    componentKey: "NotificationsPanelGrouped",
    importPath: "@/components/blocks/application/notifications-panel",
  },
  // Commerce
  {
    id: "product-grid-simple",
    name: "Product Grid — Simple",
    category: "commerce",
    description: "Catalog product cards",
    componentKey: "ProductGridSimple",
    importPath: "@/components/blocks/commerce/product-grid",
    fullWidth: true,
  },
  {
    id: "product-grid-featured",
    name: "Product Grid — Featured",
    category: "commerce",
    description: "Hero product + grid",
    componentKey: "ProductGridFeatured",
    importPath: "@/components/blocks/commerce/product-grid",
    fullWidth: true,
  },
  {
    id: "product-detail-simple",
    name: "Product Detail — Simple",
    category: "commerce",
    description: "PDP with buy actions",
    componentKey: "ProductDetailSimple",
    importPath: "@/components/blocks/commerce/product-detail",
    fullWidth: true,
  },
  {
    id: "product-detail-gallery",
    name: "Product Detail — Gallery",
    category: "commerce",
    description: "Image gallery PDP",
    componentKey: "ProductDetailGallery",
    importPath: "@/components/blocks/commerce/product-detail",
    fullWidth: true,
  },
  {
    id: "cart-drawer",
    name: "Cart Drawer",
    category: "commerce",
    description: "Slide-out shopping cart",
    componentKey: "CartDrawer",
    importPath: "@/components/blocks/commerce/cart-drawer",
  },
  {
    id: "checkout-simple",
    name: "Checkout — Simple",
    category: "commerce",
    description: "Single-page checkout",
    componentKey: "CheckoutFormSimple",
    importPath: "@/components/blocks/commerce/checkout-form",
    fullWidth: true,
  },
  {
    id: "checkout-multi",
    name: "Checkout — Multi Step",
    category: "commerce",
    description: "Stepped checkout flow",
    componentKey: "CheckoutFormMultiStep",
    importPath: "@/components/blocks/commerce/checkout-form",
    fullWidth: true,
  },
  // Content
  {
    id: "blog-list-grid",
    name: "Blog List — Grid",
    category: "content",
    description: "Article card grid",
    componentKey: "BlogListGrid",
    importPath: "@/components/blocks/content/blog-list",
    fullWidth: true,
  },
  {
    id: "blog-list-featured",
    name: "Blog List — Featured",
    category: "content",
    description: "Featured post + list",
    componentKey: "BlogListFeatured",
    importPath: "@/components/blocks/content/blog-list",
    fullWidth: true,
  },
  {
    id: "blog-post-simple",
    name: "Blog Post — Simple",
    category: "content",
    description: "Article reading layout",
    componentKey: "BlogPostSimple",
    importPath: "@/components/blocks/content/blog-post",
    fullWidth: true,
  },
  {
    id: "blog-post-sidebar",
    name: "Blog Post — With Sidebar",
    category: "content",
    description: "Article with meta sidebar",
    componentKey: "BlogPostWithSidebar",
    importPath: "@/components/blocks/content/blog-post",
    fullWidth: true,
  },
  {
    id: "docs-sidebar",
    name: "Docs Layout — Sidebar",
    category: "content",
    description: "Documentation with nav",
    componentKey: "DocsLayoutSidebar",
    importPath: "@/components/blocks/content/docs-layout",
    fullWidth: true,
  },
  {
    id: "docs-toc",
    name: "Docs Layout — With TOC",
    category: "content",
    description: "Docs with table of contents",
    componentKey: "DocsLayoutToc",
    importPath: "@/components/blocks/content/docs-layout",
    fullWidth: true,
  },
]

export function getBlockCode(entry: BlockEntry): string {
  return snippet(entry.componentKey, entry.importPath)
}
