import {
  defaultThemeBuilderConfig,
  fontFamilyMap,
  type ThemeBuilderConfig,
  type ThemeBuilderShadow,
} from "@/lib/theme-builder/types"

function oklch(l: number, c: number, h: number, alpha?: number) {
  if (alpha !== undefined) {
    return `oklch(${l} ${c} ${h} / ${alpha})`
  }
  return `oklch(${l} ${c} ${h})`
}

const shadowPresets: Record<ThemeBuilderShadow, { light: string[]; dark: string[] }> = {
  none: {
    light: [
      "0 0 0 0 transparent",
      "0 0 0 0 transparent",
      "0 0 0 0 transparent",
      "0 0 0 0 transparent",
      "0 0 0 0 transparent",
    ],
    dark: [
      "0 0 0 0 transparent",
      "0 0 0 0 transparent",
      "0 0 0 0 transparent",
      "0 0 0 0 transparent",
      "0 0 0 0 transparent",
    ],
  },
  soft: {
    light: [
      "0 1px 1px 0 oklch(0 0 0 / 0.02)",
      "0 1px 2px 0 oklch(0 0 0 / 0.03)",
      "0 2px 4px 0 oklch(0 0 0 / 0.04)",
      "0 4px 8px 0 oklch(0 0 0 / 0.05)",
      "0 8px 16px 0 oklch(0 0 0 / 0.06)",
    ],
    dark: [
      "0 1px 1px 0 oklch(0 0 0 / 0.15)",
      "0 1px 2px 0 oklch(0 0 0 / 0.2)",
      "0 2px 4px 0 oklch(0 0 0 / 0.25)",
      "0 4px 8px 0 oklch(0 0 0 / 0.3)",
      "0 8px 16px 0 oklch(0 0 0 / 0.35)",
    ],
  },
  medium: {
    light: [
      "0 1px 1px 0 oklch(0 0 0 / 0.03)",
      "0 1px 2px 0 oklch(0 0 0 / 0.04)",
      "0 2px 4px 0 oklch(0 0 0 / 0.05)",
      "0 4px 8px 0 oklch(0 0 0 / 0.06)",
      "0 8px 16px 0 oklch(0 0 0 / 0.07)",
    ],
    dark: [
      "0 1px 1px 0 oklch(0 0 0 / 0.2)",
      "0 1px 2px 0 oklch(0 0 0 / 0.25)",
      "0 2px 4px 0 oklch(0 0 0 / 0.3)",
      "0 4px 8px 0 oklch(0 0 0 / 0.35)",
      "0 8px 16px 0 oklch(0 0 0 / 0.4)",
    ],
  },
  strong: {
    light: [
      "0 1px 2px 0 oklch(0 0 0 / 0.06)",
      "0 2px 4px 0 oklch(0 0 0 / 0.08)",
      "0 4px 8px 0 oklch(0 0 0 / 0.1)",
      "0 8px 16px 0 oklch(0 0 0 / 0.12)",
      "0 12px 24px 0 oklch(0 0 0 / 0.14)",
    ],
    dark: [
      "0 1px 2px 0 oklch(0 0 0 / 0.3)",
      "0 2px 4px 0 oklch(0 0 0 / 0.35)",
      "0 4px 8px 0 oklch(0 0 0 / 0.4)",
      "0 8px 16px 0 oklch(0 0 0 / 0.45)",
      "0 12px 24px 0 oklch(0 0 0 / 0.5)",
    ],
  },
}

function sanitizeThemeId(id: string) {
  const cleaned = id
    .toLowerCase()
    .replace(/[^a-z0-9-]/g, "-")
    .replace(/^-+|-+$/g, "")
  return cleaned || "custom"
}

export function generateThemeTokensCss(
  input: Partial<ThemeBuilderConfig> = {}
): string {
  const config = { ...defaultThemeBuilderConfig, ...input }
  const id = sanitizeThemeId(config.themeId)
  const h = config.primaryHue
  const c = config.primaryChroma
  const pl = config.primaryLightness
  const shadows = shadowPresets[config.shadow]
  const fontSans = fontFamilyMap[config.font]
  const unit = config.spacingUnit
  const radius = `${config.radiusRem}rem`

  const primary = oklch(pl, c, h)
  const primaryFg = oklch(pl > 0.55 ? 0.99 : 0.14, 0.01, h)
  const bg = oklch(0.99, 0.005, h)
  const fg = oklch(0.2, 0.02, h)
  const card = oklch(1, 0, h)
  const muted = oklch(0.96, 0.01, h)
  const mutedFg = oklch(0.5, 0.02, h)
  const border = oklch(0.9, 0.01, h)
  const accent = oklch(0.94, 0.02, h)
  const ring = oklch(pl, c * 0.8, h)

  const darkBg = oklch(0.14, 0.02, h)
  const darkFg = oklch(0.96, 0.01, h)
  const darkCard = oklch(0.18, 0.02, h)
  const darkPrimary = oklch(Math.min(pl + 0.2, 0.78), c * 0.9, h)
  const darkPrimaryFg = oklch(0.14, 0.02, h)
  const darkMuted = oklch(0.24, 0.02, h)
  const darkMutedFg = oklch(0.68, 0.02, h)
  const darkBorder = oklch(1, 0, 0, 0.12)

  return `/* Generated by Decathemes Theme Builder — ${config.themeName} */
/* 1. Save as src/themes/${id}/tokens.css */
/* 2. Register in src/themes/_registry.ts */
/* 3. @import in src/styles/globals.css */

[data-theme="${id}"] {
  --background: ${bg};
  --foreground: ${fg};
  --card: ${card};
  --card-foreground: ${fg};
  --popover: ${card};
  --popover-foreground: ${fg};
  --primary: ${primary};
  --primary-foreground: ${primaryFg};
  --secondary: ${muted};
  --secondary-foreground: ${fg};
  --muted: ${muted};
  --muted-foreground: ${mutedFg};
  --accent: ${accent};
  --accent-foreground: ${fg};
  --destructive: ${oklch(0.55, 0.22, 25)};
  --destructive-foreground: ${oklch(0.99, 0, 0)};
  --border: ${border};
  --input: ${border};
  --ring: ${ring};
  --chart-1: ${oklch(pl, c, h)};
  --chart-2: ${oklch(pl, c * 0.8, h + 40)};
  --chart-3: ${oklch(pl, c * 0.7, h + 80)};
  --chart-4: ${oklch(pl, c * 0.6, h + 120)};
  --chart-5: ${oklch(pl, c * 0.5, h + 160)};
  --sidebar: ${oklch(0.98, 0.005, h)};
  --sidebar-foreground: ${fg};
  --sidebar-primary: ${primary};
  --sidebar-primary-foreground: ${primaryFg};
  --sidebar-accent: ${accent};
  --sidebar-accent-foreground: ${fg};
  --sidebar-border: ${border};
  --sidebar-ring: ${ring};
  --radius: ${radius};
  --font-sans-family: ${fontSans};
  --font-mono-family: var(--font-jetbrains-mono), ui-monospace, monospace;
  --font-serif-family: var(--font-source-serif), ui-serif, Georgia, serif;
  --font-heading-family: ${fontSans};
  --shadow-xs: ${shadows.light[0]};
  --shadow-sm: ${shadows.light[1]};
  --shadow-md: ${shadows.light[2]};
  --shadow-lg: ${shadows.light[3]};
  --shadow-xl: ${shadows.light[4]};
  --spacing-unit: ${unit}rem;
  --spacing-1: calc(var(--spacing-unit) * 1);
  --spacing-2: calc(var(--spacing-unit) * 2);
  --spacing-3: calc(var(--spacing-unit) * 3);
  --spacing-4: calc(var(--spacing-unit) * 4);
  --spacing-5: calc(var(--spacing-unit) * 5);
  --spacing-6: calc(var(--spacing-unit) * 6);
  --spacing-8: calc(var(--spacing-unit) * 8);
  --spacing-10: calc(var(--spacing-unit) * 10);
  --spacing-12: calc(var(--spacing-unit) * 12);
  --spacing-16: calc(var(--spacing-unit) * 16);
}

[data-theme="${id}"].dark {
  --background: ${darkBg};
  --foreground: ${darkFg};
  --card: ${darkCard};
  --card-foreground: ${darkFg};
  --popover: ${darkCard};
  --popover-foreground: ${darkFg};
  --primary: ${darkPrimary};
  --primary-foreground: ${darkPrimaryFg};
  --secondary: ${darkMuted};
  --secondary-foreground: ${darkFg};
  --muted: ${darkMuted};
  --muted-foreground: ${darkMutedFg};
  --accent: ${oklch(0.26, 0.03, h)};
  --accent-foreground: ${darkFg};
  --destructive: ${oklch(0.65, 0.2, 22)};
  --destructive-foreground: ${oklch(0.99, 0, 0)};
  --border: ${darkBorder};
  --input: ${oklch(1, 0, 0, 0.14)};
  --ring: ${oklch(pl + 0.15, c * 0.7, h)};
  --chart-1: ${darkPrimary};
  --chart-2: ${oklch(0.7, c * 0.8, h + 40)};
  --chart-3: ${oklch(0.75, c * 0.7, h + 80)};
  --chart-4: ${oklch(0.68, c * 0.6, h + 120)};
  --chart-5: ${oklch(0.8, c * 0.5, h + 160)};
  --sidebar: ${oklch(0.16, 0.02, h)};
  --sidebar-foreground: ${darkFg};
  --sidebar-primary: ${darkPrimary};
  --sidebar-primary-foreground: ${darkPrimaryFg};
  --sidebar-accent: ${darkMuted};
  --sidebar-accent-foreground: ${darkFg};
  --sidebar-border: ${darkBorder};
  --sidebar-ring: ${oklch(pl + 0.15, c * 0.7, h)};
  --shadow-xs: ${shadows.dark[0]};
  --shadow-sm: ${shadows.dark[1]};
  --shadow-md: ${shadows.dark[2]};
  --shadow-lg: ${shadows.dark[3]};
  --shadow-xl: ${shadows.dark[4]};
}
`
}

export function downloadThemeTokens(css: string, themeId: string): void {
  const id = sanitizeThemeId(themeId)
  const blob = new Blob([css], { type: "text/css;charset=utf-8" })
  const url = URL.createObjectURL(blob)
  const anchor = document.createElement("a")
  anchor.href = url
  anchor.download = `${id}.tokens.css`
  anchor.click()
  URL.revokeObjectURL(url)
}

export function applyBuilderPreview(css: string, themeId: string): () => void {
  if (typeof document === "undefined") return () => undefined

  const id = sanitizeThemeId(themeId)
  const styleId = "theme-builder-preview-style"
  let style = document.getElementById(styleId) as HTMLStyleElement | null

  if (!style) {
    style = document.createElement("style")
    style.id = styleId
    document.head.appendChild(style)
  }

  style.textContent = css
  const previous = document.documentElement.getAttribute("data-theme")
  document.documentElement.setAttribute("data-theme", id)

  return () => {
    if (previous) {
      document.documentElement.setAttribute("data-theme", previous)
    }
    style?.remove()
  }
}
