#!/usr/bin/env node
/**
 * Runs Lighthouse performance audits on key routes (requires production server).
 * Usage: npm run build && npm run start & npm run audit:lighthouse
 *
 * Env:
 *   AUDIT_BASE_URL — default http://localhost:3000
 *   PERF_BUDGET — minimum performance score (default 95)
 */

import { spawn } from "node:child_process"
import fs from "node:fs"
import path from "node:path"
import { fileURLToPath } from "node:url"

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const root = path.join(__dirname, "..")
const outFile = path.join(root, "src/lib/lighthouse-audit.generated.ts")
const baseUrl = process.env.AUDIT_BASE_URL ?? "http://localhost:3000"
const perfBudget = Number(process.env.PERF_BUDGET ?? "95")

const routes = [
  { key: "home", path: "/" },
  { key: "preview", path: "/preview" },
  { key: "docs", path: "/docs/getting-started" },
]

const formFactors = [
  { key: "mobile", args: ["--form-factor=mobile"] },
  { key: "desktop", args: ["--preset=desktop"] },
]

function runLighthouse(url, factor) {
  return new Promise((resolve, reject) => {
    const args = [
      url,
      "--only-categories=performance,accessibility,best-practices,seo",
      ...factor.args,
      "--output=json",
      "--quiet",
      "--chrome-flags=--headless --no-sandbox",
    ]
    const child = spawn("npx", ["lighthouse", ...args], {
      cwd: root,
      shell: true,
      stdio: ["ignore", "pipe", "pipe"],
    })
    let stdout = ""
    child.stdout.on("data", (chunk) => {
      stdout += chunk
    })
    child.on("close", (code) => {
      if (code !== 0) {
        reject(new Error(`Lighthouse failed for ${url} (${factor.key}, exit ${code})`))
        return
      }
      try {
        const report = JSON.parse(stdout)
        resolve({
          performance: Math.round(report.categories.performance.score * 100),
          accessibility: Math.round(report.categories.accessibility.score * 100),
          bestPractices: Math.round(report.categories["best-practices"].score * 100),
          seo: Math.round(report.categories.seo.score * 100),
        })
      } catch (error) {
        reject(error)
      }
    })
  })
}

async function main() {
  const results = {}

  for (const route of routes) {
    results[route.key] = {}
    for (const factor of formFactors) {
      const url = `${baseUrl}${route.path}`
      console.log(`Auditing ${url} (${factor.key})…`)
      results[route.key][factor.key] = await runLighthouse(url, factor)
    }
  }

  const allScores = []
  for (const route of Object.values(results)) {
    for (const scores of Object.values(route)) {
      allScores.push(scores.performance)
    }
  }
  const minPerformance = Math.min(...allScores)
  const auditedAt = new Date().toISOString().slice(0, 10)

  const file = `/** Generated by scripts/lighthouse-audit.mjs — do not edit manually */
export const lighthouseAuditMeta = {
  auditedAt: "${auditedAt}",
  available: true,
  perfBudget: ${perfBudget},
} as const

export const lighthouseAuditResults = ${JSON.stringify(results, null, 2)} as const

export const lighthouseMinPerformance = ${minPerformance} as const
`
  fs.writeFileSync(outFile, file)
  console.log(`Wrote ${outFile}`)
  console.log(JSON.stringify(results, null, 2))

  if (minPerformance < perfBudget) {
    console.error(
      `Performance budget failed: min ${minPerformance} < ${perfBudget} across routes/form factors`
    )
    process.exit(1)
  }
}

main().catch((error) => {
  console.error(error.message)
  process.exit(1)
})
